[build]
  publish = "."
  command = "echo 'No build step required for static site'"

[build.environment]
  # Set environment variables jika diperlukan
  NODE_VERSION = "18"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/img/*"
  to = "/static/img/:splat"
  status = 200

[[redirects]]
  from = "/content/*"
  to = "/404.html"
  status = 404

# Untuk Single Page Application (SPA) behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers untuk security dan performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache"

# Enable Netlify Identity dan Git Gateway
[[plugins]]
  package = "@netlify/plugin-git-gateway"

# Environment variables (opsional)
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"